In [1]:
import numpy as np 
# Step 1: Create three NumPy arrays of the same shape 
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[5, 6], [7, 8]]) 
arr3 = np.array([[9, 10], [11, 12]]) 
print("Array 1:\n", arr1) 
print("Array 2:\n", arr2) 
print("Array 3:\n", arr3) 
# Step 2: Merge arrays along axis 0 
merged_array = np.concatenate((arr1, arr2, arr3), axis=0) 
# Step 3: Print merged array 
print("Merged Array:\n", merged_array) 

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Array 3:
 [[ 9 10]
 [11 12]]
Merged Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
